# Generated by Django 2.1 on 2018-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180821_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='http://img.over-blog-kiwi.com/800x500-ct/2/15/25/23/20170504/ob_bddf27_fscn1365.JPG', height_field=800, max_length=200, upload_to=None, width_field=500),
        ),
    ]
