# Generated by Django 2.1 on 2018-08-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180822_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='Post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='text', max_length=40),
        ),
        migrations.AddField(
            model_name='comment',
            name='contenu',
            field=models.CharField(default='text', max_length=40),
        ),
    ]
