# Generated by Django 2.1 on 2018-08-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pseudo', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=40)),
                ('verifPassword', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
