# Generated by Django 2.1 on 2018-08-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
